datadog:
  apiKey: "348b8fedd16ca6e144d339fdc55b3220"
  site: datadoghq.com

  logs:
    enabled: true

  apm:
    enabled: true
    receiverPort: 8126

  processAgent:
    enabled: true

  dogstatsd:
    useSocketVolume: true

otel:
  enabled: true

agents:
  containerLogs:
    enabled: true

clusterAgent:
  enabled: true

kubelet:
  tlsVerify: false
