mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.95.0"
  pullPolicy: IfNotPresent

extraEnvs:
  - name: DD_API_KEY
    value: "348b8fedd16ca6e144d339fdc55b3220" 

config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
    hostmetrics:
      collection_interval: 10s
      scrapers:
        cpu:
        memory:
        disk:
        filesystem:
        network:
        load:
        paging:
        processes:

  processors:
    batch:

  exporters:
    datadog:
      api:
        site: "datadoghq.com"
        key: "${DD_API_KEY}"

  service:
    pipelines:
      metrics:
        receivers: [otlp, hostmetrics]
        processors: [batch]
        exporters: [datadog]
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [datadog]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [datadog]
