apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-otel-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
        loglevel: debug
      # Configure para enviar para Jaeger, Zipkin, Prometheus, etc
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging]