apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-otel-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
        loglevel: debug
      datadog:
        api:
          key: ${DD_API_KEY}
          site: datadoghq.com
      prometheus:
        endpoint: "0.0.0.0:8889"
        send_timestamps: true
        metric_expiration: 60m
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging, datadog]
        metrics:
          receivers: [otlp]
          exporters: [logging, prometheus]
