name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/cicd.yaml'

jobs:
  build-and-deploy:
    name: Build and Deploy to ECR and GitOps
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: ecommerce-app
      IMAGE_TAG: ${{ github.sha }}
      GITOPS_REPO: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/LeonardoVasciaveo/Desafio1.git
      GITOPS_PATH: charts/ecommerce-app

    steps:
      - name: Checkout código da aplicação
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build da imagem Docker
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./app
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push da imagem pro Amazon ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Clonar repositório GitOps
        run: |
          git clone $GITOPS_REPO gitops
          cd gitops

      - name: Atualizar values.yaml com nova tag
        run: |
          cd gitops/${{ env.GITOPS_PATH }}
          yq e '.image.tag = "${{ env.IMAGE_TAG }}"' -i values.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add values.yaml
          git commit -m "Atualizando imagem para tag $IMAGE_TAG"
          git push
