name: CI/CD Pipeline Nginx Demo

on:
  push:
    branches:
      - main
    paths:
      - 'charts/nginx-demo/**'
      - '.github/workflows/cicd.yaml'

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: eks-desafio1
  KUBE_NAMESPACE: demo
  ARGOCD_APP_NAME: nginx-demo

jobs:
  gitops-deploy:
    name: GitOps Deploy Nginx Demo
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar kubectl para EKS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Obter kubeconfig do EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Build Docker image
        run: |
          docker build -t nginx-demo:${GITHUB_SHA} -f Dockerfile .

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 339713018608.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Tag Docker image
        run: |
          docker tag nginx-demo:${GITHUB_SHA} 339713018608.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/nginx-demo:${GITHUB_SHA}

      - name: Push Docker image
        run: |
          docker push 339713018608.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/nginx-demo:${GITHUB_SHA}


