name: CI/CD Pipeline Nginx Demo

on:
  push:
    branches:
      - main
    paths:
      - 'charts/nginx-demo/**'
      - '.github/workflows/cicd.yaml'

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: eks-desafio1
  KUBE_NAMESPACE: demo
  ARGOCD_APP_NAME: nginx-demo

jobs:
  gitops-deploy:
    name: GitOps Deploy Nginx Demo
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar kubectl para EKS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Obter kubeconfig do EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Tag e Push da Imagem para o ECR
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:${{ github.sha }} 339713018608.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          docker push 339713018608.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}


